# Generated by Django 3.0.5 on 2020-04-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200411_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='on_boarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
