# Generated by Django 3.0.5 on 2020-05-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_on_boarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmedicalhistory',
            name='childhood_obesity',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
